#!/usr/bin/env bash
# Config management — read/write agent-config.yml using pure bash (no yq dependency).
# For reading YAML we parse simple key-value pairs. For writing we use templates.
# Sourced by setup.sh.

# ---------------------------------------------------------------------------
# Read a value from agent-config.yml with context-aware matching
# Usage: config_get "cloud.gcp.project_id" [file]
# Supports dot notation for nested keys. Walks the hierarchy to avoid
# matching the wrong "enabled:" in a different section.
# Limitation: only works for simple scalar values, not arrays/nested objects
# ---------------------------------------------------------------------------
config_get() {
  local key="$1" file="${2:-agent-config.yml}"
  [ -f "$file" ] || return 1

  local IFS='.'
  # shellcheck disable=SC2206
  local parts=($key)
  unset IFS

  local depth=${#parts[@]}
  local leaf="${parts[$((depth - 1))]}"

  if [ "$depth" -le 1 ]; then
    # Top-level key: match at root level (no indentation)
    grep -E "^${leaf}:" "$file" | head -1 | sed 's/^[^:]*:[[:space:]]*//' | sed 's/[[:space:]]*#.*//' | sed 's/^["'"'"']//' | sed 's/["'"'"']$//'
    return
  fi

  # Multi-level: find the section context then extract the leaf
  # Strategy: use awk to track which section we're in
  local awk_script=""
  local i

  # Build awk matching: for "plugins.mem0.enabled", look for:
  #   line matching /^\s*plugins:/ (level 0)
  #     then /^\s+mem0:/ (level 1)
  #       then /^\s+enabled:/ (level 2) → extract value
  awk_script='BEGIN { level=0; found=0 }'

  for ((i = 0; i < depth - 1; i++)); do
    local part="${parts[$i]}"
    awk_script="${awk_script}
    /^[[:space:]]*${part}:/ { level=$((i + 1)); next }"
  done

  # When we see the leaf key at the right nesting level
  awk_script="${awk_script}
  level == $((depth - 1)) && /^[[:space:]]+${leaf}:/ {
    val = \$0
    sub(/^[[:space:]]*${leaf}:[[:space:]]*/, \"\", val)
    sub(/[[:space:]]*#.*/, \"\", val)
    gsub(/^[\"']|[\"']\$/, \"\", val)
    print val
    found=1
    exit
  }
  # Reset level if we encounter a line at same or lower indent (new section)
  level > 0 && /^[^ ]/ && !/^[[:space:]]/ { level=0 }"

  local result
  result=$(awk "$awk_script" "$file" 2>/dev/null)

  if [ -n "$result" ]; then
    echo "$result"
  else
    # Fallback: simple leaf match (for flat or ambiguous structures)
    grep -E "^\s+${leaf}:" "$file" | head -1 | sed 's/.*:\s*//' | sed 's/\s*#.*//' | sed 's/^["'"'"']//' | sed 's/["'"'"']$//'
  fi
}

# ---------------------------------------------------------------------------
# Write a simple value to agent-config.yml
# Usage: config_set "cloud.gcp.project_id" "my-project"
# ---------------------------------------------------------------------------
config_set() {
  local key="$1" value="$2" file="${3:-agent-config.yml}"
  local leaf
  leaf="${key##*.}"

  if [ -f "$file" ]; then
    # Replace existing value
    sed -i.bak "s|^\(\s*${leaf}:\s*\).*|\1${value}|" "$file"
    rm -f "${file}.bak"
  fi
}

# ---------------------------------------------------------------------------
# Generate agent-config.yml from collected setup values
# Usage: config_generate <output_file>
# Expects these variables to be set:
#   AGENT_NAME, CLOUD_PROVIDER, GCP_PROJECT_ID, GCP_REGION, GCP_ZONE,
#   GCP_MACHINE_TYPE, GCP_DISK_SIZE, GCP_BUCKET_NAME, GCP_NETWORK,
#   SECRETS_PREFIX, PRIMARY_MODEL, MEM0_ENABLED, MEM0_LLM_PROVIDER,
#   MEM0_LLM_MODEL, AUDIO_ENABLED, BROWSER_ENABLED, WHATSAPP_ENABLED,
#   TIMEZONE, BACKUP_HOURS, BACKUP_RETENTION_DAYS
# ---------------------------------------------------------------------------
config_generate() {
  local output="${1:-agent-config.yml}"

  cat > "$output" << YAML
# Personal OpenClaw Agent Configuration
# Portable across cloud providers. Generated by create-openclaw-agent.
# This file does NOT contain secrets — they are stored in your cloud's secret manager.
version: 1

agent:
  name: ${AGENT_NAME:-openclaw}
  model:
    primary: ${PRIMARY_MODEL:-anthropic/claude-sonnet-4-20250514}
  models:
    anthropic/claude-opus-4-5:
      alias: opus
      cacheRetention: short
    anthropic/claude-sonnet-4-20250514:
      alias: sonnet
      cacheRetention: short
    anthropic/claude-haiku-4-5-20251001:
      alias: haiku
  context:
    pruning: cache-ttl
    ttl: 30m
    compaction: safeguard
  heartbeat: 4h
  concurrency:
    max: 1
    subagents: 2

cloud:
  provider: ${CLOUD_PROVIDER:-gcp}
  gcp:
    project_id: ${GCP_PROJECT_ID:-}
    region: ${GCP_REGION:-us-central1}
    zone: ${GCP_ZONE:-us-central1-a}
    machine_type: ${GCP_MACHINE_TYPE:-e2-medium}
    disk_size_gb: ${GCP_DISK_SIZE:-20}
    network: ${GCP_NETWORK:-default}
    bucket_name: ${GCP_BUCKET_NAME:-}

secrets:
  provider: ${SECRETS_PROVIDER:-gcp-secret-manager}
  prefix: ${SECRETS_PREFIX:-openclaw}
  keys:
    - env: ANTHROPIC_API_KEY
      id: anthropic-api-key
    - env: OPENAI_API_KEY
      id: openai-api-key
    - env: MISTRAL_API_KEY
      id: mistral-api-key
    - env: OPENCLAW_GATEWAY_TOKEN
      id: gateway-token

plugins:
  mem0:
    enabled: ${MEM0_ENABLED:-true}
    mode: open-source
    userId: ${MEM0_USER_ID:-default}
    autoCapture: true
    autoRecall: true
    topK: 3
    searchThreshold: 0.6
    llm:
      provider: ${MEM0_LLM_PROVIDER:-anthropic}
      model: ${MEM0_LLM_MODEL:-claude-haiku-4-5-20251001}
    embedder:
      provider: openai
      model: text-embedding-3-small
    vectorStore: qdrant

channels:
  whatsapp:
    enabled: ${WHATSAPP_ENABLED:-true}
    dmPolicy: pairing
    selfChatMode: false
    groupPolicy: allowlist
    mediaMaxMb: 50
    debounceMs: 3000

tools:
  audio:
    enabled: ${AUDIO_ENABLED:-true}
    language: ${AUDIO_LANGUAGE:-en}
    provider: mistral
    model: voxtral-mini-latest
  browser:
    enabled: ${BROWSER_ENABLED:-true}
    attachOnly: true
    defaultProfile: openclaw
    cdpUrl: http://127.0.0.1:9222

messages:
  ackReactionScope: group-mentions

timezone: ${TIMEZONE:-UTC}

backup:
  interval_hours: ${BACKUP_HOURS:-6}
  retention_days: ${BACKUP_RETENTION_DAYS:-90}
YAML

  ok "Generated ${output}"
}

# ---------------------------------------------------------------------------
# Generate terraform.tfvars from agent-config.yml values
# ---------------------------------------------------------------------------
config_generate_tfvars() {
  local output="${1:-terraform.tfvars}"

  cat > "$output" << TFVARS
# Auto-generated by create-openclaw-agent from agent-config.yml
# Do not edit manually — re-run setup to update.

project_id                 = "${GCP_PROJECT_ID}"
backup_bucket_name         = "${GCP_BUCKET_NAME}"
region                     = "${GCP_REGION}"
zone                       = "${GCP_ZONE}"
machine_type               = "${GCP_MACHINE_TYPE}"
disk_size_gb               = ${GCP_DISK_SIZE:-20}
timezone                   = "${TIMEZONE}"
vm_name                    = "${AGENT_NAME:-openclaw-gw}"
network                    = "${GCP_NETWORK:-default}"
backup_retention_days      = ${BACKUP_RETENTION_DAYS:-90}
backup_cron_interval_hours = ${BACKUP_HOURS:-6}
secrets_prefix             = "${SECRETS_PREFIX:-openclaw}"
TFVARS

  ok "Generated ${output}"
}
