#!/usr/bin/env bash
# Docker setup — generate compose files, run health checks, manage containers.
# Sourced by setup.sh.

# ---------------------------------------------------------------------------
# Download docker-compose.yml from OpenClaw repo
# ---------------------------------------------------------------------------
download_compose_base() {
  local dest="$1"
  local url="https://raw.githubusercontent.com/anthropics/openclaw/main/docker-compose.yml"

  info "  Downloading docker-compose.yml from OpenClaw..."
  if curl -fsSL "$url" -o "$dest" 2>/dev/null; then
    ok "docker-compose.yml downloaded"
  else
    warn "Could not download from OpenClaw repo"
    dim "You may need to copy docker-compose.yml manually from the OpenClaw repository."
    return 1
  fi
}

# ---------------------------------------------------------------------------
# Generate docker-compose.override.yml from template
# ---------------------------------------------------------------------------
generate_compose_override() {
  local dest="$1" template="$2"
  local config_dir="$3" timezone="$4"

  sed \
    -e "s|\${OPENCLAW_CONFIG_DIR}|${config_dir}|g" \
    -e "s|TZ:.*|TZ: ${timezone}|" \
    "$template" > "$dest"

  ok "docker-compose.override.yml generated"
}

# ---------------------------------------------------------------------------
# Generate .env file (non-secret values only; secrets injected via tmpfs)
# ---------------------------------------------------------------------------
generate_env() {
  local dest="$1"
  local config_dir="$2"
  local workspace_dir="${config_dir}/workspace"

  cat > "$dest" << ENV
# Generated by create-openclaw-agent
# Secrets are injected at runtime from Secret Manager via tmpfs.
# Non-secret configuration only.

OPENCLAW_CONFIG_DIR=${config_dir}
OPENCLAW_WORKSPACE_DIR=${workspace_dir}
OPENCLAW_GATEWAY_PORT=18789
OPENCLAW_BRIDGE_PORT=18790
OPENCLAW_GATEWAY_BIND=lan
OPENCLAW_IMAGE=alpine/openclaw
ENV

  ok ".env generated (non-secret values)"
}

# ---------------------------------------------------------------------------
# Wait for containers to be healthy
# ---------------------------------------------------------------------------
wait_for_healthy() {
  local timeout="${1:-120}"
  local start elapsed

  info "  Waiting for containers to be healthy (timeout: ${timeout}s)..."
  start=$(date +%s)

  while true; do
    elapsed=$(( $(date +%s) - start ))
    if [ "$elapsed" -ge "$timeout" ]; then
      fail "Timeout waiting for healthy containers"
      return 1
    fi

    local unhealthy
    unhealthy=$(docker compose ps --format json 2>/dev/null | grep -c '"unhealthy"\|"starting"' || true)
    local total
    total=$(docker compose ps --format json 2>/dev/null | wc -l | tr -d ' ')

    if [ "$total" -gt 0 ] && [ "$unhealthy" -eq 0 ]; then
      ok "All containers healthy"
      return 0
    fi

    sleep 5
  done
}

# ---------------------------------------------------------------------------
# Smoke test — verify each service responds
# ---------------------------------------------------------------------------
smoke_test() {
  step "Running smoke tests..."

  # Gateway
  if docker compose exec -T openclaw-gateway node -e "
    require('http').get('http://localhost:18789/health', r => {
      process.exit(r.statusCode === 200 ? 0 : 1);
    }).on('error', () => process.exit(1));
  " 2>/dev/null; then
    ok "Gateway responding on port 18789"
  else
    warn "Gateway health check failed (may need more time to start)"
  fi

  # Qdrant
  if docker compose exec -T qdrant wget -q --spider http://localhost:6333/healthz 2>/dev/null; then
    ok "Qdrant responding on port 6333"
  else
    warn "Qdrant health check failed"
  fi

  # Chrome
  if docker compose exec -T chrome sh -c "echo > /dev/tcp/127.0.0.1/9222" 2>/dev/null; then
    ok "Chrome CDP responding on port 9222"
  else
    warn "Chrome CDP health check failed"
  fi
}

# ---------------------------------------------------------------------------
# Configure browser in OpenClaw after containers start
# ---------------------------------------------------------------------------
configure_browser() {
  local container="${1:-openclaw-openclaw-gateway-1}"

  info "  Configuring browser (Chrome sidecar)..."
  sleep 10  # Wait for container to initialize

  if docker ps --format '{{.Names}}' | grep -q "$container"; then
    docker exec "$container" openclaw config set browser.enabled true 2>/dev/null || true
    docker exec "$container" openclaw config set browser.attachOnly true 2>/dev/null || true
    docker exec "$container" openclaw config set browser.defaultProfile openclaw 2>/dev/null || true
    docker exec "$container" openclaw config set 'browser.profiles.openclaw.cdpUrl' 'http://127.0.0.1:9222' 2>/dev/null || true
    docker exec "$container" openclaw config set 'browser.profiles.openclaw.color' '#FF4500' 2>/dev/null || true

    # Install Playwright deps
    docker exec -u root "$container" node /app/node_modules/playwright-core/cli.js install-deps chromium 2>/dev/null || true
    docker exec "$container" node /app/node_modules/playwright-core/cli.js install chromium 2>/dev/null || true

    ok "Browser configured"
  else
    warn "Container ${container} not found — browser config skipped"
  fi
}

# ---------------------------------------------------------------------------
# Install Mem0 plugin
# ---------------------------------------------------------------------------
install_mem0_plugin() {
  local container="${1:-openclaw-openclaw-gateway-1}"

  info "  Installing Mem0 plugin..."
  if docker exec "$container" node dist/index.js plugins install @mem0/openclaw-mem0 2>/dev/null; then
    ok "Mem0 plugin installed"
  else
    warn "Mem0 plugin installation failed — you can install it manually later"
    dim "docker exec $container node dist/index.js plugins install @mem0/openclaw-mem0"
  fi
}
